name: Clear old releases
description: Clear old GitHub releases
inputs:
  prefix:
    description: Delete all releases matching this prefix.
    required: false
  regex:
    description: Delete all releases matching the regular expression.
    required: false
  max-age:
    description: How old a release is allowed to be before it is deleted.
    required: true
    default: 'P1W'
  delete-tags:
    description: Delete the tag the release was created from.
    required: false
    default: 'false'
  keep-latest-releases:
    description: Keep the latest release per group. The group is specified by a named capturing group "group" in the regex input.
    required: false
    default: 'false'
  dry-run:
    description: Do not delete any releases, only log their names.
    required: false
    default: 'false'
runs:
  using: node16
  main: run.js
